<?php
/** @var Transfluent_Translate_Helper_Languages $languageHelper */
$languageHelper = Mage::helper('transfluenttranslate/languages');

/** @var Transfluent_Translate_Helper_Category $categoryHelper */
$categoryHelper = Mage::helper('transfluenttranslate/category');

$target = $this->getRequest()->getParam('target');
$source = $this->getRequest()->getParam('source');
$level = $this->getRequest()->getParam('level');
$collision_strategy = $this->getRequest()->getParam('collision');
$categories = $this->getRequest()->getParam('chk_group');

$source_store = Mage::app()->getStore($source);
//$target_store = Mage::app()->getStore($target);


//$category = Mage::getModel('catalog/category')->load($source_store->getRootCategoryId());
//var_dump($category->debug());

$quote_id = $this->getData('quote_id');

?>

    <div class="content-header">
        <h3 class="icon-head head-products"><?= $languageHelper->__('Order translations by category') ?></h3>
    </div>

    <div style="padding: 1rem; color: #ccc; margin-top: -1rem;">
        <span style="color: #666;">1. Choose source&amp;target</span> &gt; <span style="color: #666;">2. Choose categories</span> &gt; <span style="color: #666;">3. Get a quote</span> &gt; <strong style="color: black;">4. Order!</strong>
    </div>
<!--
    <div class="entry-edit" style="width: 33%; min-width: 550px;">
        <form action="<?=$this->getUrl('transfluent/adminhtml_transfluentorder/orderByCategoryStep5')?>" method="post" id="edit_form"><div><input name="form_key" type="hidden" value="<?=Mage::getSingleton('core/session')->getFormKey()?>"></div><div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend">Order</h4>
                <div class="form-buttons"></div>
            </div>
            <div class="fieldset " id="base_fieldset">
                <div class="hor-scroll">
                    <input type="hidden" name="source" value="<?=$source?>">
                    <input type="hidden" name="target" value="<?=$target?>">
                    <input type="hidden" name="level" value="<?=$level?>">
                    <input type="hidden" name="quote_id" value="<?=$quote_id?>">
                    <input type="hidden" name="collision" value="<?=$collision_strategy?>">
                    <?php
                    foreach ($categories AS $category_id) {
                        ?><input type="hidden" name="chk_group[]" value="<?=$category_id?>"><?php
                    }
                    ?>

                    TBD: Confirm order + place actual order req.!

                    <div style="margin-right: 33%;">
                        <button title="Back" type="button" class="scalable back" onclick="$(this).up('form').writeAttribute('action', '<?=$this->getUrl('transfluent/adminhtml_transfluentorder/orderByCategoryStep3')?>').submit(); return false;">Back</button>
                        <button title="Order" type="submit" class="scalable save">Order</button>
                    </div>
                </div>
            </div>
        </form></div>
-->