<?php
/** @var Transfluent_Translate_Helper_Languages $languageHelper */
$languageHelper = Mage::helper('transfluenttranslate/languages');

/** @var Transfluent_Translate_Helper_Category $categoryHelper */
$categoryHelper = Mage::helper('transfluenttranslate/category');

$level = $this->getRequest()->getParam('level');
$source = $this->getRequest()->getParam('source');
$target = $this->getRequest()->getParam('target');
$collision_strategy = $this->getRequest()->getParam('collision');
$instructions = $this->getRequest()->getParam('instructions') ? $this->getRequest()->getParam('instructions') : '';
$translate_pages = $this->getRequest()->getParam('translate_pages');
$translate_blocks = $this->getRequest()->getParam('translate_blocks');

$quote_id = $this->getData('quote_id') ? $this->getData('quote_id') :  $this->getRequest()->getParam('quote_id');
?>

<div class="content-header">
    <h3 class="icon-head head-products"><?= $languageHelper->__('Order translations for CMS content') ?></h3>
</div>

<div style="padding: 1rem; color: #ccc; margin-top: -1rem;">
    <span style="color: #666;">1. Choose source&amp;target</span> &gt; <span style="color: #666;">2. Choose CMS content</span> &gt; <strong style="color: black;">3. Get quote</strong> &gt; 4. Order!
</div>

<div class="entry-edit" style="width: 33%; min-width: 550px;">
    <form action="<?=$this->getUrl('adminhtml/Adminhtml_Transfluentorder/orderFromCmsStep4')?>" method="post" id="edit_form"><div><input name="form_key" type="hidden" value="<?=Mage::getSingleton('core/session')->getFormKey()?>"></div><div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">Get a quote</h4>
            <div class="form-buttons"></div>
        </div>
        <div class="fieldset " id="base_fieldset">
            <div class="hor-scroll">
                <input type="hidden" name="source" id="source" value="<?=$source?>">
                <input type="hidden" name="target" id="target" value="<?=$target?>">
                <input type="hidden" name="level" id="level" value="<?=$level?>">
                <input type="hidden" name="quote_id" id="quote_id" value="<?=$quote_id?>">
                <input type="hidden" name="collision" id="collision" value="<?=$collision_strategy?>">
                <input type="hidden" name="translate_pages" value="<?=$translate_pages?>">
                <input type="hidden" name="translate_blocks" value="<?=$translate_blocks?>">

                <div id="quote_canvas" style="margin-bottom: 1rem;">
                    Loading..
                </div>

                <div id="quote_instructions" style="margin-top: 2rem; margin-bottom: 1rem; display: none;">
                    <label><strong>Instructions to translators (e.g. translation tone, target audience etc.)</strong><br>
                        <textarea name="instructions" rows="4" cols="75"><?=htmlspecialchars($instructions)?></textarea></label><br>
                </div>

                <?php
                if ($level) {
                    // Missing some POST-data, such as level, hints that the quote was restored from an external link -> don't allow going back
                    ?><button title="Back" type="button" class="scalable back" onclick="$(this).up('form').writeAttribute('action', '<?=$this->getUrl('adminhtml/Adminhtml_Transfluentorder/orderFromCmsStep2')?>').submit(); return false;">Back</button><?php
                }
                ?>
                <button title="Refresh" id="quote_refresh_btn" type="submit" class="scalable save">Refresh</button>
                <button title="Order" id="quote_order_btn" type="submit" class="scalable save" onclick="OrderClick(this); return false;" disabled="disabled">Order</button>

                <p>
                    <!-- <i class="link-store-scope"></i> CMS pages and blocks will be translated from selected source store. The translated pages and blocks will be saved with the same identifier but they will be associated with the target store view only. -->
                </p>
            </div>
        </div>
    </form></div>


<script>
    function OrderClick(element) {
        if (!confirm('Are you sure?')) {
            return;
        }
        $(element).up('form').writeAttribute('action', '<?=$this->getUrl('adminhtml/Adminhtml_Transfluentorder/orderFromCmsStep5')?>').submit();
    }

    document.observe("dom:loaded", function() {
        var instructions_box = $('quote_instructions');
        var order_btn = $('quote_order_btn');
        order_btn.hide();
        var refresh_btn = $('quote_refresh_btn');
        refresh_btn.hide();
        var PollerFunction = function() {
            new Ajax.Request('<?=$this->getUrl('adminhtml/Adminhtml_Transfluentorder/orderFromCmsStep3')?>', {
                parameters: {quote_id: $F('quote_id')},
                onSuccess: function (xhr) {
                    var response = xhr.responseJSON;
                    $('quote_canvas').update(response.status);
                    switch (response.status_code) {
                        case "0":
                        case "1":
                            order_btn.hide();
                            instructions_box.hide();
                            refresh_btn.show();
                            setTimeout(PollerFunction, 2500);
                            break;
                        case "2":
                            order_btn.show().removeAttribute('disabled');
                            refresh_btn.hide();
                            instructions_box.show();
                            break;
                        case "3":
                            order_btn.hide();
                            instructions_box.hide();
                            break;
                        default:
                            order_btn.hide();
                            refresh_btn.show();
                            instructions_box.hide();
                            quote_fields.hide();
                            break;
                    }
                }
            });
        };
        PollerFunction();

    });
</script>

