<?php
/** @var Transfluent_Translate_Helper_Languages $languageHelper */
$languageHelper = Mage::helper('transfluenttranslate/languages');

/** @var Transfluent_Translate_Helper_Category $categoryHelper */
$categoryHelper = Mage::helper('transfluenttranslate/category');

$level = $this->getRequest()->getParam('level');
$source = $this->getRequest()->getParam('source');
$target = $this->getRequest()->getParam('target');
$collision_strategy = $this->getRequest()->getParam('collision');
?>

<div class="content-header">
    <h3 class="icon-head head-products"><?= $languageHelper->__('Order translations for CMS content') ?></h3>
</div>

<div style="padding: 1rem; color: #ccc; margin-top: -1rem;">
    <strong style="color: black;">1. Choose source&amp;target</strong> &gt; 2. Choose CMS content &gt; 3. Get quote &gt; 4. Order!
</div>

<div class="entry-edit" style="width: 33%; min-width: 550px;">
    <form action="<?=$this->getUrl('adminhtml/Adminhtml_Transfluentorder/orderFromCmsStep2')?>" method="post" id="edit_form"><div><input name="form_key" type="hidden" value="<?=Mage::getSingleton('core/session')->getFormKey()?>"></div><div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">Translation options</h4>
            <div class="form-buttons"></div>
        </div>
        <div class="fieldset " id="base_fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                    <tr>
                        <td class="label"><label for="username">Translator level</label></td>
                        <td class="value">
                            <select name="level">
                                <option value="native" <?=($level == 'native' ? 'selected="selected"' : '')?>>Native</option>
                                <option value="business" <?=(!$level || $level == 'business' ? 'selected="selected"' : '')?>>Business</option>
                            </select>
                        </td>
                    </tr>
                    <?php
                    $website_dropdown_options = '';
                    $websites = Mage::app()->getWebsites();
                    foreach ($websites AS $website) {
                        /** @var Mage_Core_Model_Website $website */
                        $website_dropdown_options .= '<optgroup label="' . htmlspecialchars($website->getName()) . '"></optgroup>';
                        $website_default_store = $website->getDefaultStore();
                        $website_default_store_id = $website_default_store->getId();
                        unset($website_default_store);
                        $stores = $website->getStores();
                        foreach ($stores AS $store) {
                            /** @var Mage_Core_Model_Store $store */
                            $store_locale_code = $languageHelper->GetStoreLocale($store->getCode());
                            $selected_source = (!$source && $store->getId() == $website_default_store_id || $source == $store->getId());
                            $selected_target = ($target && $store->getId() == $target);
                            $website_dropdown_options .= '<option value="' . $store->getId() . '" ' . ($selected_source ? 'SOURCE-SELECTED' : '') . ($selected_target ? 'TARGET-SELECTED' : '') . '>&nbsp;&nbsp;' . htmlspecialchars($store->getName()) . ' (' . $languageHelper->getLanguageNameByCode($store_locale_code, true) . ', ' . $store_locale_code . ')</option>';
                        }
                    }
                    ?>
                    <tr>
                        <td class="label"><label for="firstname">Translate from</label></td>
                        <td class="value">
                            <select name="source">
                                <?=str_replace(array('SOURCE-SELECTED', 'TARGET-SELECTED'), array('selected="selected"', ''), $website_dropdown_options)?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="label"><label for="firstname">Translate into</label></td>
                        <td class="value">
                            <select name="target">
                                <option></option>
                                <?=str_replace(array('TARGET-SELECTED', 'SOURCE-SELECTED'), array('selected="selected"', ''), $website_dropdown_options)?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="label"><label for="username">Existing content in target store view..</label></td>
                        <td class="value">
                            <select name="collision">
                                <option value="translated" <?=($collision_strategy == 'translated' ? 'selected="selected"' : '')?>>Skip: Assume any store specific value to be already translated</option>
                                <option value="source" <?=($collision_strategy == 'source' ? 'selected="selected"' : '')?>>Translate: Use any store specific value as source text for translation</option>
                                <option value="overwrite" <?=($collision_strategy == 'overwrite' ? 'selected="selected"' : '')?>>Delete: Overwrite store specific values with new translations</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="label"></td>
                        <td class="value" style="text-align: right;">
                            <button title="Next" type="submit" class="scalable save">Next</button>
                        </td>
                    </tr>
                    </tbody>
                </table>
                <p>
                    <i class="link-store-scope"></i> CMS pages and blocks will be saved with the same identifier as the original content but it will be associated to the target store view only. Please note that in most cases for the first round of translations, you need to choose "Translate" -option for the existing content handling because usually the main language (e.g. English) version is shown on all store views until translations are in place.<br><br><strong>Important:</strong> This tool will always send the content to be (re-)translated unless there is an <strong>exact match</strong> of previous translation. Read more: <a href="https://transfluent.zendesk.com/hc/en-us/articles/206545945-Does-Transfluent-have-translation-memory-" target="_blank">Does Transfluent have translation memory?</a>
                </p>
            </div>
        </div>
    </form></div>
