<?php
/** @var Transfluent_Translate_Helper_Languages $languageHelper */
$languageHelper = Mage::helper('transfluenttranslate/languages');
?>
<div class="content-header">
    <h3 class="icon-head head-products"><?=$languageHelper->__('Translate your Magento store') ?></h3>
</div>

<p>Transfluent's translation extension for Magento helps you to translate your webstore into multiple languages.<br>Read more about this extension <a href="https://www.transfluent.com/products/magento/" target="_blank">here</a>.</p>

<p>Your orders will be listed under your account. Visit <a href="https://www.transfluent.com/my-account/" target="_blank">My Account</a> page.</p>