<?php
$mage_admin_url = Mage::getModel('adminhtml/url');
/** @var Mage_Adminhtml_Model_Url $mage_admin_url */
$mage_admin_url->setStore(0);
$mage_admin_url->setControllerName('Adminhtml_TransfluentAccount');
$logout_url = clone $mage_admin_url;
$logout_url->setActionName('terminateSession');
$create_account_url = clone $mage_admin_url;
$create_account_url->setActionName('create');
$authenticate_url = clone $mage_admin_url;
$authenticate_url->setActionName('authenticate');
?>
<script type="text/javascript">
    //<![CDATA[
    var transfluentAccount = new TransfluentAccount({
        cUrl: '<?=$create_account_url->getUrl()?>',
        aUrl: '<?=$authenticate_url->getUrl()?>'
    });

    function transfluentCreate() {
        transfluentAccount.setCreateData();
        transfluentAccount.accountCreate();
    }

    function transfluentAuthenticate() {
        transfluentAccount.setAuthData();
        transfluentAccount.accountAuthenticate();
    }

    function transfluentLogout() {
        window.location.href = '<?=$logout_url->getUrl()?>';
        //transfluentAccount.accountLogout();
    }
    //]]>
</script>